/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新規ゲームを作成する
         * @description 参加待ちのゲームを作成し、ブラウザ用の閲覧トークン（`status_url`）と、
         *     チャット（LLM）に伝える参加コード（6文字・30分有効・1回限り）を発行します。
         *
         *     1. ブラウザは `status_url` を保持してポーリングします（参加前は 409 `waiting_for_join`）。
         *     2. プレイヤーがチャットで参加コードを伝えると、LLM が MCP ツール `join_game` を呼び出します。
         *     3. 大名が選択されると、`status_url` で自国の状況が取得できるようになります（200）。
         */
        post: operations["create_game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * セッションIDで自国の状況を取得する
         * @description セッションID（MCPツールの `session_id` と同じ値）を知っているクライアント・デバッグ向けです。
         *     Webアプリからは閲覧トークン（`/api/views/{token}/status`）を使用してください。
         */
        get: operations["session_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * defaultセッションの自国の状況を取得する
         * @description MCPツールで `session_id` を省略して遊んでいる場合（`default` セッション）の自国の状況を返します。
         *     セッションIDだけで参照できるため、公開環境ではアクセス制限を推奨します。
         */
        get: operations["default_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views/{token}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 閲覧トークンで自国の状況を取得する
         * @description Webアプリ向けのエンドポイントです。`POST /api/games` で発行された閲覧トークン、
         *     またはMCPツールの結果に付与された閲覧URLのトークンで、対応するゲームの自国の状況を返します。
         *     レスポンスにはセッションID（チャットID等）は含まれません。
         */
        get: operations["view_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description サーバーが起動していれば `ok` を返します。保存先への疎通は確認しません。
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Webで作成したゲームの情報 */
        CreatedGameDto: {
            /**
             * @description チャット（LLM）に伝える参加コード（6文字・1回限り）
             * @example VQ4X7K
             */
            join_code: string;
            /**
             * Format: date-time
             * @description 参加コードの有効期限（UTC）
             */
            join_code_expires_at: string;
            /**
             * @description プレイヤー向けの案内文
             * @example チャットで「参加コード VQ4X7K でゲームに参加して」と伝えてください
             */
            join_message: string;
            /**
             * @description 状況取得APIのパス（`GET` でポーリングする）
             * @example /api/views/777fc6d170d94495b49babeba2230e7d/status
             */
            status_url: string;
            /**
             * @description 状況取得用の閲覧トークン（32桁の16進数）。ブラウザで保持してください。
             * @example 777fc6d170d94495b49babeba2230e7d
             */
            view_token: string;
        };
        /** @description 大名の概要 */
        DaimyoDto: {
            /**
             * Format: int32
             * @description 大名ID
             * @example 7
             */
            id: number;
            /**
             * @description 大名名
             * @example 織田
             */
            name: string;
        };
        /**
         * @description 機械判定用のエラーコード
         * @enum {string}
         */
        ErrorCode: "view_not_found" | "session_not_found" | "daimyo_not_selected" | "waiting_for_join" | "internal_error";
        /** @description エラーレスポンス */
        ErrorResponse: {
            /** @description 機械判定用のエラーコード */
            code: components["schemas"]["ErrorCode"];
            /**
             * @description 人間向けのメッセージ（日本語）
             * @example チャット側の参加待ちです。チャットで参加コードを伝えてください
             */
            message: string;
        };
        /** @description 自領1国分の状況 */
        KuniStatusDto: {
            /**
             * Format: int32
             * @description 兵
             */
            hei: number;
            /**
             * Format: int32
             * @description 国ID
             * @example 7
             */
            id: number;
            /**
             * Format: int32
             * @description 人口
             */
            jinko: number;
            /**
             * Format: int32
             * @description 金
             */
            kin: number;
            /**
             * Format: int32
             * @description 石高
             */
            kokudaka: number;
            /**
             * Format: int32
             * @description 米
             */
            kome: number;
            /**
             * Format: int32
             * @description 町
             */
            machi: number;
            /**
             * @description 国名
             * @example 尾張
             */
            name: string;
            /**
             * Format: int32
             * @description 忠誠度（0〜100）
             */
            tyu: number;
        };
        /**
         * @description 自国の状況
         *
         *     返すのは「自国の状況」「ターン数」「他国がどの大名の領地か」のみです。
         *     他国の資源（兵・金など）は含みません。
         */
        MyStatusDto: {
            /** @description プレイヤーが選択している大名（自国） */
            daimyo: components["schemas"]["DaimyoDto"];
            /** @description 自領の一覧（国ID順） */
            my_kunis: components["schemas"]["KuniStatusDto"][];
            /** @description 他国の一覧（国ID順）。どの大名の領地かのみを示す */
            other_kunis: components["schemas"]["OtherKuniDto"][];
            /**
             * Format: int32
             * @description 現在のターン（1始まり）
             * @example 1
             */
            turn: number;
        };
        /** @description 他国1国分の情報（支配大名のみ） */
        OtherKuniDto: {
            /** @description この国を支配している大名 */
            daimyo: components["schemas"]["DaimyoDto"];
            /**
             * Format: int32
             * @description 国ID
             * @example 6
             */
            id: number;
            /**
             * @description 国名
             * @example 三河
             */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_game: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ゲームを作成しました */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedGameDto"];
                };
            };
            /** @description 保存先へのアクセスに失敗しました（`internal_error`） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    session_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description セッションID（前後の空白は除去。空なら `default`）
                 * @example discord_12345
                 */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自国の状況 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyStatusDto"];
                };
            };
            /** @description セッションが存在しません（`session_not_found`） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 大名が未選択です（`daimyo_not_selected`） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバー内部のエラー（`internal_error`） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    default_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自国の状況 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyStatusDto"];
                };
            };
            /** @description セッションが存在しません（`session_not_found`） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 大名が未選択です（`daimyo_not_selected`） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバー内部のエラー（`internal_error`） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    view_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 閲覧トークン（32桁の16進数）
                 * @example 777fc6d170d94495b49babeba2230e7d
                 */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自国の状況 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyStatusDto"];
                };
            };
            /** @description 閲覧トークンが無効です（`view_not_found`） */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description チャット側の参加待ち（`waiting_for_join`）、または大名が未選択（`daimyo_not_selected`） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description サーバー内部のエラー（`internal_error`） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 稼働中 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example ok */
                    "text/plain": string;
                };
            };
        };
    };
}
